alias c='clear'
alias cp='cp -i'
alias df='df -h'
alias du='du -h'
alias emd='emacs --daemon'
alias em='emacsclient -c'
alias ll='ls -l'
alias ln='ln -i'
alias ls='ls --color=auto'
alias mv='mv -i'
alias pe='eval $(poetry env activate)'
alias py='python3'
alias python='python3'
alias rm='rm -i'
