#!/bin/bash

# Linux system installer
# Author: Simone Gentili (g3nsy)

if [ "$#" -gt 1 ]; then
  echo "Too many arguments" >&2
  exit 1
fi
if [ "$#" -eq 1 ] && ! [ "$1" = "--symbolic-link" ] && ! [ "$1" = "-s" ]; then
  echo "Invalid parameter: $1" >&2
  exit 1
fi

SCRIPT_DIR=$(realpath $(dirname $0))
CONFIGS=$SCRIPT_DIR/configs
LISTS_DIR=$SCRIPT_DIR/lists
AUR=$LISTS_DIR/aur
PYTHON=$LISTS_DIR/python
PACMAN=$LISTS_DIR/pacman
UCONFIG=$LISTS_DIR/uconfig
SCONFIG=$LISTS_DIR/sconfig

for file in $AUR $PACMAN $PYTHON $UCONFIG $SCONFIG $CONFIGS; do
  if [ ! -e $file ]; then
    echo "Missing required file: $file" >&2
    exit 1
  fi
done

sudo pacman -S --needed --noconfirm --overwrite "*" - <$PACMAN
[ $? -ne 0 ] && exit 1

if ! type yay 2>/dev/null; then
  YAY_CLONE_PATH=$SCRIPT_DIR/yay
  YAY_REPO_URL=https://aur.archlinux.org/yay-bin.git
  [ -e $YAY_CLONE_PATH ] && rm -rfv $YAY_CLONE_PATH
  git clone $YAY_REPO_URL $YAY_CLONE_PATH &&
    cd $YAY_CLONE_PATH &&
    makepkg -si --clean --noconfirm &&
    cd .. &&
    rm -rfv $YAY_CLONE_PATH &&
    yay -S --needed --noconfirm - <$AUR
fi

# User configuration files
while IFS=: read -r filename destination; do
  SRC=$CONFIGS/$filename
  DST=~/$destination
  DST_PARENT_NODE=$(dirname $DST)
  mkdir -pv $DST_PARENT_NODE
  [ -e $DST ] && rm -rfv $DST
  cp -rv $1 $SRC $DST # $1: --symbolic-link or -s or empty string
done <"$UCONFIG"

# System-wide configuration files
while IFS=: read -r filename destination; do
  SRC=$CONFIGS/$filename
  DST_PARENT_NODE=$(dirname $destination)
  sudo mkdir -pv $DST_PARENT_NODE
  sudo cp -rv --remove-destination $SRC $destination
done <"$SCONFIG"

pip install -qr $PYTHON
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm &&
  ~/.tmux/plugins/tpm/scripts/install_plugins.sh
sudo grub-mkconfig -o /boot/grub/grub.cfg
