server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"
preview_length = 80

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = ["-nb", "#191918", "-nf", "#c5c5c5", "-sb", "#A89071", "-sf", "#c5c5c5", "-fn", "CaskaydiaCove Nerd Font:pixelsize=13"]

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
