server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"
preview_length = 80

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = ["-nb", "#150d12", "-nf", "#c4c2c3", "-sb", "#66602D", "-sf", "#c4c2c3", "-fn", "CaskaydiaCove Nerd Font:pixelsize=13"]

[custom_finder]
program = "dmenu -nb #150d12 -nf #c4c2c3 -sb #66602D -sf #c4c2c3 -fn 'CaskaydiaCove Nerd Font:pixelsize=13'"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
