server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"
preview_length = 80

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = ["-nb", "#070707", "-nf", "#c1c1c1", "-sb", "#4C4C4C", "-sf", "#c1c1c1", "-fn", "CaskaydiaCove Nerd Font:pixelsize=13"]

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
