#!/usr/bin/env bash

SCRIPT_PATH=$(readlink -f "$0")

wal -a 92 -i $1 # -a 92: tmux transparency

if [[ $? -ne 0 ]]; then
  exit 1
fi

# -- telegram-desktop
walogram -s

# -- chromium
chromium-wal
pidof chromium && killall chromium && chromium --restore-last-session &

# -- dunst
[ -f "$HOME/.cache/wal/colors.sh" ] && . "$HOME/.cache/wal/colors.sh"
cat ~/.config/dunst/dunstrc | head -n 460 >~/.config/dunst/tmp
echo "[urgency_low]
    # IMPORTANT: colors have to be defined in quotation marks.
    # Otherwise the "#" and following would be interpreted as a comment.
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 10
    # Icon for notifications with low urgency, uncomment to enable
    #default_icon = /path/to/icon
[urgency_normal]
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 10
    override_pause_level = 30
    # Icon for notifications with normal urgency, uncomment to enable
    #default_icon = /path/to/icon
[urgency_critical]
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 0
    override_pause_level = 60
    # Icon for notifications with critical urgency, uncomment to enable
    #default_icon = /path/to/Icon
" >>~/.config/dunst/tmp
mv ~/.config/dunst/tmp ~/Codes/dots/configs/dunst
pidof dunst && killall dunst && dunst &
sleep 2

# --discord
pywal-discord -t default

# -- tmux
tmux_config=$(cat ~/.tmux.conf)
tmux_config=$(echo "$tmux_config" | sed -e "s/@minimal-tmux-bg \"#[^']*\"/@minimal-tmux-bg \"$color7\"/")
tmux_config=$(echo "$tmux_config" | sed -e "s/@minimal-tmux-fg \"#[^']*\"/@minimal-tmux-fg \"$color2\"/")
echo "$tmux_config" >~/.tmux.conf
tmux source-file ~/.tmux.conf

# -- gtk
"$(dirname $SCRIPT_PATH)"/change-color-gtk/change-color.sh -t /usr/share/themes -o change-color-gtk-theme <(echo -e "BG=$color0\nBTN_BG=$color0\nBTN_FG=$color7\nFG=$color7\nGRADIENT=0.0\nHDR_BTN_BG=$color0\nHDR_BTN_FG=$color4\nHDR_BG=$color0\nHDR_FG=$color7\nROUNDNESS=0\nSEL_BG=$color1\nSEL_FG=$color7\nSPACING=3\nTXT_BG=$color0\nTXT_FG=$color7\nWM_BORDER_FOCUS=$color2\nWM_BORDER_UNFOCUS=$color1\n")
killall -HUP xsettingsd

# -- lightdm
cp -fv $1 /usr/share/wallpapers/lightdm-wallpaper

# -- notify
notify-send "Theme changed"
