#!/usr/bin/env bash

SCRIPT_PATH=$(readlink -f "$0")

eval "$(awk 'NR==1{print "wallpaper=\"" $0 "\""} NR==2{print "fastfetch_image=\"" $0 "\""} NR==3{print "color_name=\"" $0 "\""}' "$1")"

wal -a 92 -i ~/Codes/dots/themes/wallpapers/$wallpaper # -a 92: tmux transparency

if [[ $? -ne 0 ]]; then
  exit 1
fi

# -- telegram-desktop
walogram -s

# -- chromium
chromium-wal
pidof chromium && killall chromium && chromium --restore-last-session &

# -- dunst
[ -f "$HOME/.cache/wal/colors.sh" ] && . "$HOME/.cache/wal/colors.sh"
cat ~/.config/dunst/dunstrc | head -n 460 >~/.config/dunst/tmp
echo "[urgency_low]
    # IMPORTANT: colors have to be defined in quotation marks.
    # Otherwise the "#" and following would be interpreted as a comment.
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 10
    # Icon for notifications with low urgency, uncomment to enable
    #default_icon = /path/to/icon
[urgency_normal]
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 10
    override_pause_level = 30
    # Icon for notifications with normal urgency, uncomment to enable
    #default_icon = /path/to/icon
[urgency_critical]
    background = \"$color0\"
    foreground = \"$color1\"
    frame_color = \"$color2\"
    timeout = 0
    override_pause_level = 60
    # Icon for notifications with critical urgency, uncomment to enable
    #default_icon = /path/to/Icon
" >>~/.config/dunst/tmp
mv ~/.config/dunst/tmp ~/Codes/dots/configs/dunst
pidof dunst && killall dunst && dunst &
sleep 2

# --discord
pywal-discord -t default

# -- tmux
tmux_config=$(cat ~/.tmux.conf)
tmux_config=$(echo "$tmux_config" | sed -e "s/@minimal-tmux-bg \"#[^']*\"/@minimal-tmux-bg \"$color7\"/")
tmux_config=$(echo "$tmux_config" | sed -e "s/@minimal-tmux-fg \"#[^']*\"/@minimal-tmux-fg \"$color2\"/")
echo "$tmux_config" >~/.tmux.conf
tmux source-file ~/.tmux.conf

# -- spotify
pywal-spicetify marketplace

# icons (always before updating xsettingsd)
papirus-folders --color $color_name

# -- gtk
oomox-cli ~/.cache/wal/colors-oomox -t /usr/share/themes
# killall -HUP xsettingsd
killall xsettingsd
xsettingsd &

# -- lightdm
cp -fv $wallpaper /usr/share/wallpapers/lightdm-wallpaper

# -- fastfetch
[ -d "$HOME/.config/fastfetch/pngs" ] && rm -rfv ~/.config/fastfetch/pngs
mkdir ~/.config/fastfetch/pngs
cp -fv "$HOME/Codes/dots/themes/pngs/$fastfetch_image" ~/.config/fastfetch/pngs/

# -- notify
notify-send "Theme changed"
