#!/bin/bash

case "$1" in
"dark")
  echo ":: dark theme selected"
  cp -fv ~/Codes/dots/configs/dark-xsettingsd ~/.xsettingsd
  cp -fv ~/Codes/dots/configs/rofi-dark-theme ~/.config/rofi/colors.rasi
  cp -fv ~/Codes/dots/configs/polybar-dark-theme ~/.config/polybar/colors.ini
  cp -fv ~/Codes/dots/configs/dark-lightdm /etc/lightdm/lightdm-gtk-greeter.conf
  sed -i 's/light/dark/g' ~/.config/alacritty/alacritty.toml
  sed -i 's/light/dark/g' ~/.config/keepassxc/keepassxc.ini
  feh --bg-fill /usr/share/backgrounds/dark-wallpaper.png
  ;;
"light")
  echo ":: light theme selected"
  cp -fv ~/Codes/dots/configs/light-xsettingsd ~/.xsettingsd
  cp -fv ~/Codes/dots/configs/rofi-light-theme ~/.config/rofi/colors.rasi
  cp -fv ~/Codes/dots/configs/polybar-light-theme ~/.config/polybar/colors.ini
  cp -fv ~/Codes/dots/configs/light-lightdm /etc/lightdm/lightdm-gtk-greeter.conf
  sed -i 's/dark/light/g' ~/.config/alacritty/alacritty.toml
  sed -i 's/dark/light/g' ~/.config/keepassxc/keepassxc.ini
  feh --bg-fill /usr/share/backgrounds/light-wallpaper.png
  ;;
esac

killall -HUP xsettingsd # reload configuration
